"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
APP_NAME = "MyManifest_Char"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'iconfinder__m_2560433.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Requesting manifest",
        'CFBundleVersion': "4",
        'CFBundleShortVersionString': "4",
        'NSHumanReadableCopyright': "Copyright @ 2019, Jack Xiao, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
