"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
APP_NAME = "MyManifest"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'iconfinder__m_2560433.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
